### ISSUE TITLE
Compliant with alternatives

### ISSUE THREAD

**Issue by ericis** [anycli/tslint#18]
**oclif** styles are not compliant with other standards like:
* Angular projects
* AirBnB `tslint-config-airbnb` projects

Suggest either adopt Angular CLI defaults, AirBnB standards, or modify the CLI to present the option to install alternative style configurations.

I personally used:
1. `oclif multi mycli`
2. `cd ./mycli`
3. `npm i tslint-config-airbnb --save-dev`
4. `npm uninstall @oclif/tslint --save-dev`
5. Modify `./tslint.json`
```
{
    "extends": "tslint-config-airbnb"
}
```
6. `npm run test`
7. Fix files with errors

**Comment by jdx** [comment]
We have our own default lint standard already. I don't want to change it or maintain alternatives.
